-- Run this in Supabase Dashboard → SQL Editor.
create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  requirements text not null,
  created_at timestamptz not null default now()
);

alter table public.inquiries enable row level security;

-- Static-site visitors may submit an inquiry. There is no public read policy.
drop policy if exists "Anyone can submit an inquiry" on public.inquiries;
create policy "Anyone can submit an inquiry"
  on public.inquiries
  for insert
  to anon
  with check (
    char_length(trim(name)) between 1 and 160
    and char_length(trim(phone)) between 3 and 40
    and char_length(trim(email)) between 3 and 320
    and char_length(trim(requirements)) between 1 and 10000
  );

-- Optional image file uploads require a private Supabase Storage bucket and
-- appropriate upload policy. This starter form captures the inquiry fields;
-- it accepts a JPEG/PNG selection for the visitor but does not upload the file.
